<a href="https://colab.research.google.com/github/saiRajAj/DAVIS/blob/main/introduction_to_numpy_%26_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a Python program to create a NumPy array with five integers and display it.


In [3]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


Write a program to find the data type of a NumPy array.

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


Write a program to access the first and last element of a NumPy array.




In [9]:
print(arr[0])
print(arr[-1])

10
50


Write a program to slice a NumPy array and print elements from index 1 to 3.

In [12]:
print(arr[1:4])

[20 30 40]


Write a program to display the first three elements of a NumPy array using slicing.

In [14]:
print(arr[:3])

[10 20 30]


Write a program to extract the last two elements of a NumPy array using slicing.


In [16]:
print(arr[-2:])

[40 50]
