<a href="https://colab.research.google.com/github/saiRajAj/DAVIS/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1D NumPy Array Questions**

Write a program to create a 1D NumPy array with five elements entered by the user.


In [1]:
import numpy as np

In [3]:
arr = np.array([int(input()) for i in range(5)])

10
20
30
40
50


In [4]:
print(arr)

[10 20 30 40 50]


Write a program to find the length of a 1D NumPy array.

In [5]:
len = len(arr)
print(len)

5


Write a program to access the first, middle, and last element of a NumPy array.


In [6]:
print(arr[0], arr[len//2], arr[len-1])

10 30 50


Write a program to slice a NumPy array from index 2 to 5.


In [7]:
print(arr[2:6])

[30 40 50]


Write a program to print all elements of a NumPy array using a loop.


In [9]:
for element in arr:
  print(element, end=" ")

10 20 30 40 50 

Write a program to add 10 to each element of a NumPy array.


In [10]:
print(arr + 10)

[20 30 40 50 60]


Write a program to find the sum and average of elements in a 1D NumPy array.

In [12]:
print('Sum : ', np.sum(arr))
print('Average : ', np.average(arr))

Sum :  150
Average :  30.0


Write a program to find the maximum and minimum value in a NumPy array.


In [13]:
print('Maximum : ', np.max(arr))
print('Minimum : ', np.min(arr))

Maximum :  50
Minimum :  10


Write a program to reverse a NumPy array using slicing.

In [17]:
print(arr[::-1])

[50 40 30 20 10]


Write a program to check whether a specific element exists in a NumPy array.


In [18]:
element = int(input('Enter Element to search : '))
print(element in arr)

Enter Element to search : 10
True


# **2D NumPy Array Questions**

Write a program to create a 2D NumPy array of size 3×3 and display it.

In [19]:
arr = np.array([[int(input()) for i in range(3)] for j in range(3)])

10
20
30
40
50
60
70
80
90


In [20]:
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


Write a program to find the shape of a 2D NumPy array.

In [21]:
print('Shape of array is : ', arr.shape)

Shape of array is :  (3, 3)


Write a program to access a specific element from a 2D array using row and column index.

In [22]:
element = int(input('Enter Element to search : '))
print(np.where(arr == element))

Enter Element to search : 50
(array([1]), array([1]))


Write a program to extract the first row and first column from a 2D NumPy array.


In [28]:
print('Row : ', arr[0:1])
print('Column : ', arr[:,0])

Row :  [[10 20 30]]
Column :  [10 40 70]


Write a program to slice a 2D NumPy array to get a sub-matrix.


In [29]:
print(arr[1:3, 1:3])

[[50 60]
 [80 90]]


Write a program to calculate the sum of all elements in a 2D NumPy array.


In [30]:
print(np.sum(arr))

450


Write a program to calculate row-wise sum of a 2D NumPy array.


In [31]:
print(np.sum(arr, axis=1))

[ 60 150 240]


Write a program to calculate column-wise average of a 2D NumPy array.


In [34]:
print(np.average(arr, axis=0))

[40. 50. 60.]


Write a program to multiply each element of a 2D NumPy array by 2.


In [35]:
print(arr * 2)

[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]


Write a program to find the maximum value from each row of a 2D NumPy array.


In [36]:
print(np.max(arr, axis=1))

[30 60 90]
