<a href="https://colab.research.google.com/github/saiRajAj/DAVIS/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
print(arr)

[1 2 3 4 5]


In [5]:
print(arr[1:3])

[2 3]


In [6]:
print(arr[:4])

[1 2 3 4]


In [7]:
print(arr[2:])

[3 4 5]


In [10]:
print(arr[:-3])

[1 2]


**Function in Numpy**

In [12]:
arr = np.arange(1,6)
print(arr)

[1 2 3 4 5]


In [13]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [14]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [15]:
marks = np.array([70, 80, 50, 90, 60])
print('Sum : ',np.sum(marks))
print('Mean : ',np.mean(marks))
print('Max : ', np.max(marks))

Sum :  350
Mean :  70.0
Max :  90


#2D Numpy Array

In [24]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [18]:
print(arr.shape)

(3, 3)


#2d Array accessing Elements
array[row_index,column_index]

In [19]:
print(arr[0,1])

20


In [20]:
print(arr[2,1])

80


**2D Slicing Numpy**

In [30]:
print(arr[0:2,0:2])

[[10 20]
 [40 50]]


In [22]:
print(arr[1:3,1:3])

[[50 60]
 [80 90]]


In [31]:
print(arr.ndim)

2


In [38]:
arr = np.array([[10, 20, 30, 11], [40, 50, 60, 22], [70, 80, 90, 33]])
print(arr)

[[10 20 30 11]
 [40 50 60 22]
 [70 80 90 33]]


In [40]:
print(arr[1:,2:])

[[60 22]
 [90 33]]


In [43]:
print(arr * 2)

[[ 20  40  60  22]
 [ 80 100 120  44]
 [140 160 180  66]]


In [45]:
print("Average marks of students : ", np.mean(marks,axis=1))

Average marks of students :  [80.         61.66666667 91.66666667]


In [46]:
print("Average marks of subjects : ", np.mean(marks,axis=0))

Average marks of subjects :  [72.66666667 82.33333333 78.33333333]


# 3D Array

In [37]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Data-Types in Numpy